### ISSUE TITLE
Folder structure does not allow ST-Github integration

### ISSUE THREAD

**Issue by dkorunic** [codersaur/SmartThings#29]
Please take look at developers' documentation (http://docs.smartthings.com/en/latest/tools-and-ide/github-integration.html) and rename folders as specified: DTHs should reside in devicetypes/dth1.src, devicetypes/dth2.src etc. and Smart Apps in smartapps/app1.src and smartapps/app2.src folders respectively.

This way that folders have been created here, user is forced to copy/paste code in IDE making future updates (and code change detection) a pain.

**Comment by scrool** [comment]
I have already opened PR #21 for this.

**Comment by dkorunic** [comment]
@scrool Agreed, sorry I have missed that. Closing the issue in favor of #21
