### ISSUE TITLE
Remove spaces in path

### ISSUE THREAD

**Issue by dbradmit** [codersaur/SmartThings#4]
Can we please remove any spaces in the path name? This is causing issues when users try to install directly to SmartThings rather than copying pasting. Replacing the spaces with underscores should solve the issue.

For example:

*https://api.github.com/repos/codersaur/SmartThings/contents/smartapps/InfluxDB_Logger*
instead of
*https://api.github.com/repos/codersaur/SmartThings/contents/smartapps/InfluxDB Logger*

**Comment by dubbedout** [comment]
I had the same issue, I couldn't access my SmartApps on IDE and ST determined it was this repo causing the issues due to the space.

**Comment by codersaur** [comment]
Fixed
