### ISSUE TITLE
using Aeon Home Energy Meter no things screen

### ISSUE THREAD

**Issue by cblomart** [codersaur/SmartThings#6]
using Aeon Home Energy Meter, the thing screen on the android smartthings app fails to load...

**Comment by codersaur** [comment]
Should now be fixed in v1.03.
https://github.com/codersaur/SmartThings/tree/master/devices/aeon-home-energy-meter
Please let me know if it works for you.

**Comment by cblomart** [comment]
Works like a charm! thx
